xiekeyang/oci-discovery

ref-engine-discovery.md

1. README had suggested to use `python` upper that v3. So need not to `python3` command name in makefile. The command  name of `python3` make those who use `python3.5`, `python3.5m` failed by prompting `python3 cmd not found`.
2. URL example should use \` \` to wrap, other it will be shown as super link, unable to visit.
Signed-off-by: xiekeyang <keyang.xie@gmail.com>
@wking

Fix hyperlink unable to visit

---

oci_discovery/ref_engine_discovery/__init__.py

Instead of catching `URLError`.  `URLError` is [for protocol-level issues][1] (e.g. wrapping an `SSLError` if you attempt an HTTPS connection to a server that does not speak TLS).  They do not have much structure.
`HTTPError`, on the other hand, is [for things like 400 errors][2] and they do support things like [`geturl`][3].
[1]: https://docs.python.org/3/library/urllib.error.html#urllib.error.URLError
[2]: https://docs.python.org/3/library/urllib.error.html#urllib.error.HTTPError
[3]: https://docs.python.org/3/library/urllib.request.html#urllib.request.urlopen

oci_discovery/ref_engine_discovery: Catch HTTPError for ref_engine.resolve

---

README.md

I expect the code I wrote only works on Python 3, and [PEP 394][1] suggests `python3` for that.  I got the `Makefile` entries right in 89e3eb5 (#2), but botched this one.
[1]: https://www.python.org/dev/peps/pep-0394/#recommendation

README: Replace 'python' with 'python3'

---

README.md
oci_discovery/ref_engine/oci_index_template.py
oci_discovery/uri_template/__init__.py
oci_discovery/uri_template/test.py
requirements.txt

Python's `.format()` can handle things like `{host}`, but there's a lot more than that in RFC 6570.  Instead of rolling our own implementation, punt to the [uritemplate package][1].  The [license is][2]:
> BSD-3-Clause OR Apache-2.0
which should be compatible with the [OCI's Apache-2.0 requirement][3], even if that requirement applies to third-party dependencies, which is not clear to me.
[1]: https://pypi.python.org/pypi/uritemplate
[2]: https://github.com/python-hyper/uritemplate/blob/3.0.0/LICENSE
[3]: https://www.opencontainers.org/about/governance

oci_discovery/uri_template: Stub for URI Template expansion

---

oci_discovery/ref_engine_discovery/ancestor_hosts.py
oci_discovery/ref_engine_discovery/test_ancestor_hosts.py

Like `localhost`.  These are unlikely to be portable, but they do match the [`host` ABNF][1]:
```abnf
host          = IP-literal / IPv4address / reg-name
reg-name      = *( unreserved / pct-encoded / sub-delims )
unreserved    = ALPHA / DIGIT / "-" / "." / "_" / "~"
pct-encoded   = "%" HEXDIG HEXDIG
sub-delims    = "!" / "$" / "&" / "'" / "(" / ")"
/ "*" / "+" / "," / ";" / "="
```
[1]: https://tools.ietf.org/html/rfc3986#appendix-A

oci_discovery/ref_engine_discovery/ancestor_hosts.py: Handle dotless names

---

README.md
oci_discovery/ref_engine_discovery/__init__.py
oci_discovery/ref_engine_discovery/__main__.py

With `--protocol` replacing the old `--https-only`.  With these changes, you can do things like:
$ python3 -m oci_discovery.ref_engine_discovery --protocol http --port 8080 '[::1]/app#1.0'
when testing locally.
Fixes #9 (although there are probably other ways we could address that too).

oci_discovery/ref_engine_discovery/__main__.py: Add --protocol and --port

---

ref-engine-discovery.md

These slipped in as a copy/paste error in d1535110 (#2).

ref-engine-discovery.md: Fix "refEngines" -> "casEngines" typo's

---

README.md
oci_discovery/ref_engine_discovery/__main__.py
ref-engine-discovery.md

For consistency with “Ref-Engine Protocols” and such.  I've only used title case for document headers (e.g. specification names); subsections use “Sentence case” headers like “Ref-engine discovery”.
This is a very minor nit, but it's easier to get consistency on these things if we are consistent from the beginning :).

*: Fix “Ref-engine” → “Ref-Engine” for title-case

---

oci_discovery/host_based_image_names/__init__.py
oci_discovery/host_based_image_names/test.py
oci_discovery/ref_engine_discovery/ancestor_hosts.py
oci_discovery/ref_engine_discovery/test_ancestor_hosts.py

To fully implement the ABNF-defined host rule from RFC 3986.

oci_discovery/host_based_image_names: Improve host regexp

---

cas-template.md
index-template.md
oci_discovery/ref_engine/oci_index_template.py
oci_discovery/ref_engine/test_oci_index_template.py

As discussed [here][1] and [here][2].  This allows for entries that can move with the base content.  For example, you could have a ref-engines object at `file:///srv/app/ref-engines.json` with content like:
```json
{
"refEngines": [
{
"protocol": "oci-index-template-v1",
"uri": "index.json"
}
],
"casEngines": [
{
"protocol": "oci-cas-template-v1",
"uri": "blobs/{algorithm}/{encoded}"
}
]
}
```
that now expands to `file:///srv/app/index.json`, `file:///srv/app/blobs/sha256/e97…`, etc.  And those references would still expand correctly if you moved the whole `/srv/app` directory to `/srv/new-app` and referenced the ref-engines object from `file:///srv/new-app/ref-engines.json`.
[1]: https://tools.ietf.org/html/rfc3986#section-4.2
[2]: https://tools.ietf.org/html/rfc3986#section-5

*-template: Cover relative references

---

README.md
oci_discovery/fetch_json/__init__.py
oci_discovery/fetch_json/test.py
oci_discovery/ref_engine/dummy.py
oci_discovery/ref_engine/oci_index_template.py
oci_discovery/ref_engine/test_oci_index_template.py
oci_discovery/ref_engine_discovery/__init__.py
oci_discovery/ref_engine_discovery/test.py

From [here][1]:
> Note that if the retrieval was the result of a redirected request, the last URI used (i.e., the URI that resulted in the actual retrieval of the representation) is the base URI.
This fills in remaining Python functionality left off from #21.  Ref-engine discovery and ref-engine APIs now also return dicts that include a `uri` key representing this URI, which allows their consumers to also perform reference resolution.  For example, tools consuming the Merkle roots may need the URI from which those roots were extracted in order to resolve a CAS-engine URI reference.
[1]: https://tools.ietf.org/html/rfc3986#section-5.1.3

oci_discovery/fetch_json: Return the final URI along with the JSON

---

tools/cmd/vendor/github.com/opencontainers/image-spec/specs-go/v1/annotations.go
tools/cmd/vendor/github.com/opencontainers/image-spec/specs-go/v1/config.go
tools/cmd/vendor/github.com/opencontainers/image-spec/specs-go/v1/descriptor.go
tools/cmd/vendor/github.com/opencontainers/image-spec/specs-go/v1/index.go
tools/cmd/vendor/github.com/opencontainers/image-spec/specs-go/v1/layout.go
tools/cmd/vendor/github.com/opencontainers/image-spec/specs-go/v1/manifest.go
tools/cmd/vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
tools/cmd/vendor/github.com/opencontainers/image-spec/specs-go/version.go
tools/cmd/vendor/github.com/opencontainers/image-spec/specs-go/versioned.go
tools/cmd/vendor/golang.org/x/net/context/context.go
tools/cmd/vendor/golang.org/x/net/context/context_test.go
tools/cmd/vendor/golang.org/x/net/context/ctxhttp/ctxhttp.go
tools/cmd/vendor/golang.org/x/net/context/ctxhttp/ctxhttp_17_test.go
tools/cmd/vendor/golang.org/x/net/context/ctxhttp/ctxhttp_pre17.go
tools/cmd/vendor/golang.org/x/net/context/ctxhttp/ctxhttp_pre17_test.go
tools/cmd/vendor/golang.org/x/net/context/ctxhttp/ctxhttp_test.go
tools/cmd/vendor/golang.org/x/net/context/go17.go
tools/cmd/vendor/golang.org/x/net/context/pre_go17.go
tools/cmd/vendor/golang.org/x/net/context/withtimeout_test.go

Signed-off-by: xiekeyang <xiekeyang@huawei.com>

add vendor

---

oci_discovery/uri_template/test.py

This snuck in with #7, sorry :/.

oci_discovery/uri_template/test: Remove trailing whitespace

---

tools/cmd/resolve.go
tools/refenginediscovery/refenginediscovery.go
tools/refenginediscovery/type.go

We usually use this type in arrays, but the type itself represents a single CAS-engine config.

tools: Fix "ResolvedCASEngines" -> "ResolvedCASEngine" typos

---

tools/refengine/root.go

To follow the:
> … complete sentence that begins with the name of the element it describes.
[recommendation][1].
[1]: https://blog.golang.org/godoc-documenting-go-code

tools/refengine/root: Lead Root comment with "Root"

---

tools/engine/config_test.go
tools/refengine/root.go
tools/refengine/root_test.go

And add tests to confirm this.  I expect this is unlikely to matter in practice, but I think it makes sense to have the unmarshalled JSON be more like [PUT][1] than [PATCH][2].  For what it's worth, the Go implementation seems to prefer PATCH (at least as of 1.9).
Also add similar tests to `tools/engine/config_test.go`, although we didn't need changes to the implementation to get those to pass.
[1]: https://tools.ietf.org/html/rfc7231#section-4.3.4
[2]: https://tools.ietf.org/html/rfc5789

tools/refengine/root: Clear MediaType and URI if unset in JSON

---

tools/cmd/resolve.go
tools/refengine/interface.go

If the ref-engine we're checking returns no results, keep going (even if it didn't return an error).  Also document the “ref-engine knows it doesn't have that name” results in the `Engine.Get` interface.

tools/cmd/resolve: Keep iterating through ref-engines on empty Get

---

tools/README.md
tools/cmd/resolve.go
tools/engine/config.go
tools/engine/reference.go
tools/engine/reference_test.go
tools/refengine/interface.go
tools/refengine/root.go
tools/refenginediscovery/refenginediscovery.go
tools/refenginediscovery/type.go

Previously these were not provided in the output JSON.
To store the data during resolution, create a new `resolvedName` type.  That type extends the usual `MerkleRoot` JSON with a new `casEngines` property that is a sibling of `MerkleRoot`'s `root` and `uri` properties.  To get the sibling serialization, we need a little `MarshalJSON` wrapper for `resolvedName`, but we don't need to bother with `UnmarshalJSON` because this isn't a public library type.
Rename `allRoots` to `resolvedNames`, because each key in the map is an image name.  Each value in the map may contain several roots (`resolveName`s), so `allRoots` wasn't particularly clear.
Move `refenginediscovery.ResolvedCASEngine` to `engine.Reference`.  This gives us a shorter name, and lets us recycle some code via the new (private) …

tools: Expose ref-engine discovery casEngines

---

.mailmap

Preferring the most common commit author:
$ git log --no-merges | grep '^Author.*keyang' | sort | uniq -c | sort -n | tail -n1
5 Author: xiekeyang <xiekeyang@huawei.com>
Docs for the format in the MAPPING AUTHORS section of `git-shortlog(1)`.

.mailmap: Consilidate Keyang's emails

---

README.md
cas-template.md
index-template.md
ref-engine-protocols.md
tools/cmd/resolve.go
tools/refenginediscovery/engines.go
tools/refenginediscovery/wellknownuri/wellknownuri.go
tools/refenginediscovery/xdg/stringlengthsort.go
tools/refenginediscovery/xdg/stringlengthsort_test.go
tools/refenginediscovery/xdg/type.go
tools/refenginediscovery/xdg/xdg.go
tools/refenginediscovery/xdg/xdg_test.go
well-known-uri-ref-engine-discovery.md
xdg-ref-engine-discovery.md

This allows tools (like `oci-discovery`) to use local files to provide ref- and CAS-engine suggestions for arbitrary image names.  Besides the general flexibility, this demonstrates the flexibility of the discovery approach and underscores the fact that the well-known URI approach is just one of many possible approaches.
The commits running up to the tip are smaller pivots to setup for the new protocol.  I can spin them out into their own PRs if you like, or break any of the commits up into even smaller pivots if that will help.  If/when we land the Markdown spec for the XDG protocol, I'll file a separate PR updating the Python package.

xdg-ref-engine-discovery: Add an XDG ref-engine discovery protocol

---

README.md
oci_discovery/README.md
tools/README.md

Because they're no more canonical than the Go-specific docs in `tools/README.md`.

oci_discovery/README: Pull Python-specific docs out of the main README

---

oci_discovery/uri_template/test.py

This gives us complete coverage for the `uri_template` package, as measured by:
```
$ pip install --user coverage
$ python -m coverage run -m unittest discover
$ python -m coverage report | grep uri_template
oci_discovery/uri_template/__init__.py        10      0   100%
oci_discovery/uri_template/test.py            33      5    85%
```
Incomplete coverage in `test.py` is acceptable; the unexercised statements are due to:
* The presence of `uritemplate` on my local system, so I don't excercise the `ImportError` fallback.  The fallback allows the tests to run on systems without `uritemplate`, so we want to keep it.
* The lack of buggy double entries, so I don't exercise the “entries in both” failure.  This guard protects devs from adding buggy double entries, so we want to keep it.
* The …

oci_discovery/uri_template/test: Test URITemplate.__str__

---

oci_discovery/fetch_json/test.py

In `test_redirect`, avoiding:
```
$ make test-python
…
Traceback (most recent call last):
File "/.../oci_discovery/fetch_json/test.py", line 166, in test_redirect
self.assertEqual(fetched, {'uri': final_uri, 'json': expected})
NameError: name 'expected' is not defined
…
```
Fixing a copy/paste error from #55.

oci_discovery/fetch_json/test: Fix undefined expected

---

oci_discovery/ref_engine_discovery/test_xdg.py

Adding tests for the `yield_from_ref_engines_object` `ValueError` handling and the `FileNotFoundError` handling.

oci_discovery/ref_engine_discovery/test_xdg: Complete xdg coverage
